"use client";

import { useState } from "react";
import Image from "next/image";
import {
  Code2,
  Bot,
  LineChart,
  ShieldCheck,
  BarChart2,
  Stethoscope,
  Navigation,
  ShoppingCart,
  Award,
  FileText,
} from "lucide-react";

export default function EmergingTrendsAndApplications() {
  // --- 1. EMERGING TRENDS DATA ---
  const emergingTrends = [
    {
      id: "dl-nn",
      title: "Deep Learning / Neural Networks",
      description:
        "Deep Learning / Neural Network Solutions.",
    },
    {
      id: "quantum",
      title: "Next Generation Quantum Algorithms",
      description:
        "Quantum Algorithms for the Next Generation of Quantum Computing Systems",
    },
    {
      id: "edge",
      title: "Real-time Edge Computing",
      description:
        "Real-Time Data and Analytics on Edge Devices",
    },
    {
      id: "xai",
      title: "Transparent AI (XAI)",
      description:
        "Clear and Interpretable AI Algorithms",
    },
    {
      id: "opt",
      title: "Advanced Optimisation Algorithms",
      description:
        "Advanced Algorithms for Logistics, Financial and Engineering Optimisation Problems",
    },
    {
      id: "blockchain",
      title: "Blockchain Algorithms",
      description:
        "Secure & Decentralized Algorithms for Computation",
    },
    {
      id: "auto-alg",
      title: "Automated Algorithm Design",
      description:
        "Algorithms Generated by Artificial Intelligence for Complex Problem Solving",
    },
    {
      id: "rt-proc",
      title: "Real-Time Processing Algorithms",
      description:
        "Fast Decision-Making Algorithms",
    },
  ];

  const [activeTrend, setActiveTrend] = useState(emergingTrends[2]); // Default: Real-time Edge Computing

  // --- 2. APPLICATIONS OF ALGORITHM DATA ---
  const applications = [
    {
      title: "Software Development",
      iconSrc: "/images/subject-matter-experts/algorithm/Algorithm-Design-Analysis.webp",
      desc: "efficient coding and optimising the system and/or application.",
      icon: Code2,
    },
    {
      title: "Artificial Intelligence",
      iconSrc: "/images/subject-matter-experts/algorithm/Data-Structure-Optimisation.webp",
      desc: "developing machine learning and creating \"smart\" computers.",
      icon: Bot,
    },
    {
      title: "Data Science",
      iconSrc: "/images/subject-matter-experts/algorithm/Computational-Complexity.webp",
      desc: "analysis, statistical modelling, and visualisation of data.",
      icon: LineChart,
    },
    {
      title: "Cybersecurity",
      iconSrc: "/images/subject-matter-experts/algorithm/Machine-Learning-Algorithms.webp",
      desc: "using cryptography and authenticating users to detect security threats.",
      icon: ShieldCheck,
    },
    {
      title: "Financial Markets",
      iconSrc: "/images/subject-matter-experts/algorithm/Network-Graph-Algorithms.webp",
      desc: "creating algorithms for trading and risk analysis.",
      icon: BarChart2,
    },
    {
      title: "Healthcare",
      iconSrc: "/images/subject-matter-experts/algorithm/Parallel-Distributed-Algorithms.webp",
      desc: "analysing medical data and diagnosing patients.",
      icon: Stethoscope,
    },
    {
      title: "Transportation",
      iconSrc: "/images/subject-matter-experts/algorithm/Heuristic-and-Metaheuristic-Algorithms.webp",
      desc: "determining the best route and managing traffic.",
      icon: Navigation,
    },
    {
      title: "E-commerce",
      iconSrc: "/images/subject-matter-experts/algorithm/Numerical-Algorithm.webp",
      desc: "creating recommendation systems and optimising searches.",
      icon: ShoppingCart,
    },
  ];

  // --- 3. EDITORS DATA ---
  const editors = [
    {
      name: "Dr. Robert Klein",
      degree: "PhD in Computer Science",
      flag: "🇺🇸",
      avatar: "/images/subject-matter-experts/algorithm/Dr.-Robert-Klein.webp",
      experience: "15 years of experience",
      manuscripts: "200+ manuscripts edited",
    },
    {
      name: "Dr. Ananya Iyer",
      degree: "PhD in Data Science",
      flag: "🇺🇸",
      avatar: "/images/subject-matter-experts/algorithm/Dr.-Ananya-Iyer-1.webp",
      experience: "12 years of experience",
      manuscripts: "180+ manuscripts edited",
    },
    {
      name: "Dr. David Chen",
      degree: "PhD in Computational Engineering",
      flag: "🇺🇸",
      avatar: "/images/subject-matter-experts/algorithm/Dr.-David-Chen.webp",
      experience: "11 years of experience",
      manuscripts: "150+ manuscripts edited",
    },
  ];

  return (
    <section className="max-w-6xl mx-auto px-4 py-12 space-y-16 bg-white font-sans text-gray-800">
      {/* SECTION 1: EMERGING TRENDS IN ALGORITHM */}
      <div className="space-y-6">
        <div className="space-y-1">
          <h2 className="text-xl md:text-2xl font-bold text-[#1e2e2b]">
            Emerging Trends in Algorithm
          </h2>
          <p className="text-xs text-gray-600 font-medium">
            Trends in Computing, Data Science, and Intelligent Systems through Advanced Algorithms:
          </p>
        </div>

        {/* Dynamic Matrix Selector Container */}
        <div className="bg-[#f8f9f9] p-4 md:p-6 rounded border border-gray-200">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
            {emergingTrends.map((trend) => {
              const isActive = activeTrend.id === trend.id;
              return (
                <button
                  key={trend.id}
                  onClick={() => setActiveTrend(trend)}
                  className={`py-3 px-2 text-center text-[11px] font-semibold transition-colors duration-150 border ${isActive
                      ? "bg-[#12433e] text-white border-[#12433e]"
                      : "bg-[#edf0f0] text-gray-800 border-gray-200 hover:bg-gray-200"
                    }`}
                >
                  {trend.title}
                </button>
              );
            })}
          </div>

          {/* Dynamic Active Trend Box */}
          <div className="mt-3 bg-white p-4 border border-gray-200 rounded-sm text-left">
            <h3 className="text-xs font-bold text-gray-900">
              {activeTrend.title}
            </h3>
            <p className="text-[11px] text-gray-500 mt-1 leading-relaxed">
              {activeTrend.description}
            </p>
          </div>
        </div>

        <p className="text-xs text-gray-600 leading-relaxed max-w-5xl">
          All these trends represent a shift away from traditional approaches to computing, intelligence, and Efficiency. Today's engineering of Advanced Algorithms is revolutionising how we think about computing, intelligence and efficiency.
        </p>
      </div>

      {/* SECTION 2: APPLICATIONS OF ALGORITHM */}
      <div className="space-y-6">
        <div className="space-y-2">
          <h2 className="text-xl md:text-2xl font-bold text-[#1e2e2b]">
            Applications of Algorithm
          </h2>
          <p className="text-xs text-gray-600 leading-relaxed">
            The area of algorithms is one of the most important areas in computer science because it uses computational logic to develop solutions to real-world problems using math and logic. The following are some of the many areas in which algorithms work:
          </p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-12 gap-6 items-start">
          {/* Applications Items */}
          <div className="md:col-span-7 space-y-3.5">
            {applications.map((app, idx) => {
              const AppIcon = app.icon;
              return (
                <div key={idx} className="flex items-start gap-2.5">
                  <div className="p-1 bg-gray-100 text-gray-700 shrink-0 rounded">
                    {"iconSrc" in app && app.iconSrc ? (
                      <Image
                        src={app.iconSrc}
                        alt=""
                        width={24}
                        height={24}
                        className="object-contain w-4 h-4 shrink-0"
                      />
                    ) : (
                      <AppIcon className="w-4 h-4" />
                    )}
                  </div>
                  <p className="text-xs text-gray-700 leading-snug">
                    <span className="font-bold text-gray-900">{app.title}</span> – {app.desc}
                  </p>
                </div>
              );
            })}
          </div>

          {/* Workspace Image */}
          <div className="md:col-span-5 relative h-72 md:h-80 w-full rounded overflow-hidden border border-gray-200 shadow-sm">
            <Image
              src="/images/subject-matter-experts/algorithm/Applications-of-Algorithm.webp"
              alt="Developer workstation with code on dual monitors"
              fill
              className="object-cover"
            />
          </div>
        </div>
      </div>

      {/* SECTION 3: WHERE OUR AUTHORS PUBLISH */}
      <div className="space-y-6 text-center">
        <div className="space-y-2">
          <h2 className="text-xl md:text-2xl font-bold text-[#1e2e2b]">
            Where Our Authors Publish
          </h2>
          <div className="w-10 h-0.5 bg-[#12433e] mx-auto" />
          <p className="text-xs text-gray-600 max-w-2xl mx-auto pt-1">
            Our authors share Pubrica's expert content in top-tier journals and conferences, ensuring global recognition and impact.
          </p>
        </div>

        <div className="max-w-3xl mx-auto bg-white border border-gray-200 rounded p-5 shadow-sm text-left grid grid-cols-1 sm:grid-cols-12 gap-6 items-center">
          <div className="sm:col-span-4 relative h-56 w-full rounded overflow-hidden shadow">
            <Image
              src="/images/subject-matter-experts/algorithm/sample-works-13-1.webp"
              alt="Algorithms and Computation Journal Cover"
              fill
              className="object-cover"
            />
          </div>

          <div className="sm:col-span-8 space-y-2.5 text-xs text-gray-700">
            <p>
              <span className="font-bold text-gray-900">Paper Title: </span>
              Advanced Optimization Algorithms for Large-Scale Data Processing
            </p>
            <p>
              <span className="font-bold text-gray-900">Author: </span>
              John R. Anderson
            </p>
            <p>
              <span className="font-bold text-gray-900">Journal Name: </span>
              Journal of Algorithms and Computation
            </p>
            <p>
              <span className="font-bold text-gray-900">Publisher: </span>
              Elsevier
            </p>
            <p>
              <span className="font-bold text-gray-900">Impact factor: </span>
              4.2
            </p>
          </div>
        </div>
      </div>

      {/* SECTION 4: OUR EXPERT ALGORITHM EDITORS */}
      <div className="space-y-6 text-center">
        <div className="space-y-2">
          <h2 className="text-xl md:text-2xl font-bold text-[#1e2e2b]">
            Our Expert Algorithm Editors
          </h2>
          <p className="text-xs text-gray-600 max-w-3xl mx-auto">
            Pubrica's team of subject matter experts brings strong computational and analytical expertise to deliver precise and innovative solutions.
          </p>
        </div>

        <div className="grid grid-cols-1 sm:grid-cols-3 gap-4">
          {editors.map((editor, idx) => (
            <div
              key={idx}
              className="bg-[#d2e7e3] rounded-2xl p-4 border border-[#b8ded7] shadow-sm flex flex-col justify-between"
            >
              <div className="flex items-center gap-3 mb-3">
                <div className="relative w-10 h-10 rounded-full overflow-hidden border-2 border-white shrink-0">
                  <Image
                    src={editor.avatar}
                    alt={editor.name}
                    fill
                    className="object-cover"
                  />
                </div>
                <div className="text-left">
                  <h3 className="text-xs font-bold text-gray-900 flex items-center gap-1">
                    <span>{editor.flag}</span>
                    {editor.name}
                  </h3>
                  <p className="text-[11px] text-gray-600">{editor.degree}</p>
                </div>
              </div>

              <div className="border-t border-[#aed7cf] pt-2.5 flex items-center justify-between text-[11px] text-gray-700 font-medium">
                <div className="flex items-center gap-1">
                  <Award className="w-3.5 h-3.5 text-[#12433e]" />
                  <span>{editor.experience}</span>
                </div>
                <div className="flex items-center gap-1">
                  <FileText className="w-3.5 h-3.5 text-[#12433e]" />
                  <span>{editor.manuscripts}</span>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
}