"use client";

import { useState } from "react";
import Image from "next/image";
import {
  Code2,
  Bot,
  LineChart,
  ShieldCheck,
  BarChart2,
  Stethoscope,
  Navigation,
  ShoppingCart,
  Award,
  FileText,
} from "lucide-react";
import EmergingTrendsSection from "@/components/common/EmergingTrendsSection";
import ApplicationsSection from "@/components/common/ApplicationsSection";
import ExpertEditorsSection, { ExpertEditorItem } from "@/components/common/ExpertEditorsSection";
import WhereAuthorsPublish, { AuthorPublicationData } from "@/components/common/WhereAuthorsPublish";

export default function EmergingTrendsAndApplications() {
  // --- 1. EMERGING TRENDS DATA ---
  const emergingTrends = [
    {
      id: "dl-nn",
      title: "Deep Learning / Neural Networks",
      description: "Deep Learning / Neural Network Solutions.",
    },
    {
      id: "quantum",
      title: "Next Generation Quantum Algorithms",
      description:
        "Quantum Algorithms for the Next Generation of Quantum Computing Systems",
    },
    {
      id: "edge",
      title: "Real-time Edge Computing",
      description: "Real-Time Data and Analytics on Edge Devices",
    },
    {
      id: "xai",
      title: "Transparent AI (XAI)",
      description: "Clear and Interpretable AI Algorithms",
    },
    {
      id: "opt",
      title: "Advanced Optimisation Algorithms",
      description:
        "Advanced Algorithms for Logistics, Financial and Engineering Optimisation Problems",
    },
    {
      id: "blockchain",
      title: "Blockchain Algorithms",
      description: "Secure & Decentralized Algorithms for Computation",
    },
    {
      id: "auto-alg",
      title: "Automated Algorithm Design",
      description:
        "Algorithms Generated by Artificial Intelligence for Complex Problem Solving",
    },
    {
      id: "rt-proc",
      title: "Real-Time Processing Algorithms",
      description: "Fast Decision-Making Algorithms",
    },
  ]
  const [activeTrend, setActiveTrend] = useState(emergingTrends[2]); // Default: Real-time Edge Computing

  // --- 2. APPLICATIONS OF ALGORITHM DATA ---
  const applications = [
    {
      title: "Software Development",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Algorithm-Design-Analysis.webp",
      desc: "efficient coding and optimising the system and/or application.",
      icon: Code2,
    },
    {
      title: "Artificial Intelligence",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Data-Structure-Optimisation.webp",
      desc: 'developing machine learning and creating "smart" computers.',
      icon: Bot,
    },
    {
      title: "Data Science",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Computational-Complexity.webp",
      desc: "analysis, statistical modelling, and visualisation of data.",
      icon: LineChart,
    },
    {
      title: "Cybersecurity",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Machine-Learning-Algorithms.webp",
      desc: "using cryptography and authenticating users to detect security threats.",
      icon: ShieldCheck,
    },
    {
      title: "Financial Markets",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Network-Graph-Algorithms.webp",
      desc: "creating algorithms for trading and risk analysis.",
      icon: BarChart2,
    },
    {
      title: "Healthcare",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Parallel-Distributed-Algorithms.webp",
      desc: "analysing medical data and diagnosing patients.",
      icon: Stethoscope,
    },
    {
      title: "Transportation",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Heuristic-and-Metaheuristic-Algorithms.webp",
      desc: "determining the best route and managing traffic.",
      icon: Navigation,
    },
    {
      title: "E-commerce",
      iconSrc:
        "/images/subject-matter-experts/algorithm/Numerical-Algorithm.webp",
      desc: "creating recommendation systems and optimising searches.",
      icon: ShoppingCart,
    },
  ];

  const publication: AuthorPublicationData = {
    imageSrc:
      "/images/subject-matter-experts/algorithm/sample-works-13-1.webp",
    imageAlt: "Algorithms and Computation Journal Cover",
    paperTitle:
      "Advanced Optimization Algorithms for Large-Scale Data Processing",
    author: "John R. Anderson",
    publisher: "Elsevier",
    journalName: "Journal of Algorithms and Computation",
    impactFactor: "4.2",
  };

  // --- 3. EDITORS DATA ---
  const editors: ExpertEditorItem[] = [
    {
      name: "Dr. Robert Klein",
      degree: "PhD in Computer Science",
      flag: "/images/country/gb.png",
      avatar:
        "/images/subject-matter-experts/algorithm/Dr.-Robert-Klein.webp",
      experience: "15 years of experience",
      manuscripts: "200+ manuscripts edited",
    },
    {
      name: "Dr. Ananya Iyer",
      degree: "PhD in Data Science",
      flag: "/images/country/us.png",
      avatar:
        "/images/subject-matter-experts/algorithm/Dr.-Ananya-Iyer-1.webp",
      experience: "12 years of experience",
      manuscripts: "180+ manuscripts edited",
    },
    {
      name: "Dr. David Chen",
      degree: "PhD in Computational Engineering",
      flag: "/images/country/us.png",
      avatar:
        "/images/subject-matter-experts/algorithm/Dr.-David-Chen.webp",
      experience: "11 years of experience",
      manuscripts: "150+ manuscripts edited",
    },
  ];

  return (
    <section className="max-w-6xl mx-auto px-4 py-6 space-y-16 bg-white font-sans text-gray-800">
      {/* SECTION 1: EMERGING TRENDS IN ALGORITHM */}
      <EmergingTrendsSection
        title="Emerging Trends in Algorithm"
        description="Trends in Computing, Data Science, and Intelligent Systems through Advanced Algorithms:"
        trends={emergingTrends}
        footerText="All these trends represent a shift away from traditional approaches to computing, intelligence, and Efficiency. Today’s engineering of Advanced Algorithms is revolutionising how we think about computing, intelligence and efficiency."
      />

      {/* SECTION 2: APPLICATIONS OF ALGORITHM */}
      <ApplicationsSection
        title="Applications of Algorithm"
        description="The area of algorithms is one of the most important areas in computer science because it uses computational logic to develop solutions to real-world problems using math and logic. The following are some of the many areas in which algorithms work:"
        applications={applications}
        imageSrc="/images/subject-matter-experts/algorithm/Applications-of-Algorithm.webp"
        imageAlt="Applications of Algorithm"
      />

      {/* SECTION 3: WHERE OUR AUTHORS PUBLISH */}
      <WhereAuthorsPublish
        title="Where Our Authors Publish"
        description="Our authors share Pubrica's expert content in top-tier journals and conferences, ensuring global recognition and impact."
        publication={publication}
      />
      {/* SECTION 4: OUR EXPERT ALGORITHM EDITORS */}
      <ExpertEditorsSection
        title="Our Expert Algorithm Editors"
        description="Pubrica's team of subject matter experts brings strong computational and analytical expertise to deliver precise and innovative solutions."
        editors={editors}
      />
    </section>
  );
}