import { MetadataRoute } from "next";
import { getPosts } from "@/lib/payload";

export const revalidate = 3600;

const SITE_URL = process.env.NEXT_PUBLIC_SITE_URL || "https://pubrica.com";

// Every real, resolvable static route in the app, grouped the way the site itself is structured.
const STATIC_ROUTES: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"] }[] = [
  { path: "", priority: 1.0, changeFrequency: "weekly" },

  // Top-level sections
  { path: "/services", priority: 0.9, changeFrequency: "weekly" },
  { path: "/Industries", priority: 0.9, changeFrequency: "weekly" },
  { path: "/subject-matter-experts", priority: 0.9, changeFrequency: "weekly" },
  { path: "/about-us", priority: 0.8, changeFrequency: "monthly" },
  { path: "/academy", priority: 0.8, changeFrequency: "weekly" },
  { path: "/insights", priority: 0.8, changeFrequency: "weekly" },
  { path: "/blog", priority: 0.8, changeFrequency: "weekly" },
  { path: "/careers", priority: 0.7, changeFrequency: "weekly" },
  { path: "/call-for-papers", priority: 0.7, changeFrequency: "weekly" },
  { path: "/contact", priority: 0.7, changeFrequency: "monthly" },

  // Industries
  { path: "/Industries/biosimilar", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/biotechnology", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/cosmeceutical-research", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/cosmetics", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/foods-nutraceuticals", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/generics", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/medical-device", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/nutraceutical-research", priority: 0.7, changeFrequency: "monthly" },
  { path: "/Industries/pharmaceutical", priority: 0.7, changeFrequency: "monthly" },

  // About Us
  { path: "/about-us/life-science", priority: 0.6, changeFrequency: "monthly" },
  { path: "/about-us/life-sciences", priority: 0.6, changeFrequency: "monthly" },
  { path: "/about-us/medicine", priority: 0.6, changeFrequency: "monthly" },
  { path: "/about-us/our-editors", priority: 0.6, changeFrequency: "monthly" },
  { path: "/about-us/physical-sciences-engineering", priority: 0.6, changeFrequency: "monthly" },
  { path: "/quality", priority: 0.6, changeFrequency: "monthly" },
  { path: "/quality/confidentiality", priority: 0.5, changeFrequency: "monthly" },
  { path: "/quality/quality-assurance", priority: 0.5, changeFrequency: "monthly" },
  { path: "/quality-standards", priority: 0.5, changeFrequency: "monthly" },
  { path: "/therapeutic-expertise", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strategic-partnerships-memberships", priority: 0.6, changeFrequency: "monthly" },
  { path: "/strategic-partnerships-memberships/publisher", priority: 0.5, changeFrequency: "monthly" },
  { path: "/strategic-partnerships-memberships/university", priority: 0.5, changeFrequency: "monthly" },
  { path: "/editorial-panel", priority: 0.5, changeFrequency: "monthly" },
  { path: "/scientific-editor-profile", priority: 0.5, changeFrequency: "monthly" },
  { path: "/editor-speak", priority: 0.5, changeFrequency: "monthly" },
  { path: "/editor-application", priority: 0.5, changeFrequency: "monthly" },

  // Academy hubs
  { path: "/academy/artical", priority: 0.6, changeFrequency: "weekly" },
  { path: "/academy/artical/be-wordly-wise", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/artical/parallel-construction", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/artical/phrasing-it-right", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/artical/tense", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/artical/written-content", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/articles", priority: 0.6, changeFrequency: "weekly" },
  { path: "/academy/articles/journal-selection", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/flow-diagram", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/grammer", priority: 0.6, changeFrequency: "weekly" },
  { path: "/academy/industry-news", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/journal-templates", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/manuscript-guidelines", priority: 0.6, changeFrequency: "weekly" },
  { path: "/academy/manuscript-guidelines/collaborative-process", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/manuscript-submission", priority: 0.6, changeFrequency: "weekly" },
  { path: "/academy/promoting-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/publication-ethics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/qa-forum", priority: 0.6, changeFrequency: "weekly" },
  { path: "/academy/referencing-style", priority: 0.6, changeFrequency: "weekly" },
  { path: "/academy/referencing-style/business-sources", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/referencing-style/my-tryst", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/research-promotion", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/research-publication", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/response-to-reviewer", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/response-to-reviewer/responding-to-reviewer-comments-revise-research-paper", priority: 0.5, changeFrequency: "monthly" },
  { path: "/academy/tables-figures", priority: 0.5, changeFrequency: "monthly" },

  // Careers
  { path: "/careers/job-posting", priority: 0.5, changeFrequency: "weekly" },

  // Legal / misc
  { path: "/contact-us", priority: 0.5, changeFrequency: "monthly" },
  { path: "/cookie-policy", priority: 0.3, changeFrequency: "yearly" },
  { path: "/do-not-sell-any-information", priority: 0.3, changeFrequency: "yearly" },
  { path: "/privacy-policy", priority: 0.3, changeFrequency: "yearly" },
  { path: "/terms", priority: 0.3, changeFrequency: "yearly" },
  { path: "/terms-and-condition", priority: 0.3, changeFrequency: "yearly" },
  { path: "/terms-and-conditions", priority: 0.3, changeFrequency: "yearly" },
  { path: "/ethics", priority: 0.4, changeFrequency: "yearly" },
  { path: "/faq", priority: 0.5, changeFrequency: "monthly" },
  { path: "/our-guarantee", priority: 0.5, changeFrequency: "monthly" },
  { path: "/our-published-papers", priority: 0.5, changeFrequency: "monthly" },
  { path: "/how-it-works", priority: 0.5, changeFrequency: "monthly" },
  { path: "/order-now", priority: 0.6, changeFrequency: "monthly" },
  { path: "/order-journal-selection-now", priority: 0.5, changeFrequency: "monthly" },
  { path: "/refer-a-friend", priority: 0.4, changeFrequency: "monthly" },
  { path: "/global-partner-program", priority: 0.5, changeFrequency: "monthly" },
  { path: "/university-support", priority: 0.5, changeFrequency: "monthly" },
  { path: "/publishers", priority: 0.4, changeFrequency: "monthly" },
  { path: "/lab-assistance", priority: 0.4, changeFrequency: "monthly" },
  { path: "/testimonial", priority: 0.5, changeFrequency: "monthly" },
  { path: "/sample", priority: 0.4, changeFrequency: "monthly" },
  { path: "/gold-pack", priority: 0.4, changeFrequency: "monthly" },
  { path: "/silver-pack", priority: 0.4, changeFrequency: "monthly" },
  { path: "/platinum-pack", priority: 0.4, changeFrequency: "monthly" },
  { path: "/get-newsletter", priority: 0.4, changeFrequency: "monthly" },
  { path: "/meta-data-collection-brochures", priority: 0.4, changeFrequency: "monthly" },
  { path: "/research-services-brochures", priority: 0.4, changeFrequency: "monthly" },
  { path: "/scientific-communication-brochures", priority: 0.4, changeFrequency: "monthly" },
  { path: "/pmda-regulatory-writing", priority: 0.4, changeFrequency: "monthly" },
  { path: "/ich-guidelines-pharmaceutical-regulations", priority: 0.4, changeFrequency: "monthly" },
  { path: "/good-publication-practice-gpp-guidelines", priority: 0.4, changeFrequency: "monthly" },
  { path: "/disability-adjusted-life-year-dally-overview", priority: 0.4, changeFrequency: "monthly" },
  { path: "/genex-in-cancer-progression", priority: 0.4, changeFrequency: "monthly" },
  { path: "/ligand-identification", priority: 0.4, changeFrequency: "monthly" },
  { path: "/journal", priority: 0.4, changeFrequency: "monthly" },
  { path: "/journal-of-internal-medicine-demo", priority: 0.3, changeFrequency: "monthly" },
  { path: "/farmatting", priority: 0.3, changeFrequency: "monthly" },
  { path: "/thank-you", priority: 0.1, changeFrequency: "yearly" },
  { path: "/website-tree-structure", priority: 0.2, changeFrequency: "monthly" },

  // Services hubs
  { path: "/services/academic-editorial-services", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/ai-tools-for-academic-publishing", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/copy-editing-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/development-editing-service", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/editorial-services-case-studies", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/forensic-and-quality-audit-service", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/forensic-and-quality-audit-service/forensic-audit-complete-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/implement-a-flawless-editorial-quality-assurance-checklist", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/permission-and-metadata-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/revisioning-and-localisation-service", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/tools-standards-academic-editing", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/academic-editorial-services/visual-and-accessibility-editing-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/ai-ml-support", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/ai-ml-support/video-image-analytics", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/bioinformatics", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/bioinformatics/epigenetics-bioinformatics-biostatistical-methods", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/continuing-medical-education-cme-content-development", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/continuing-medical-education-cme-content-development/what-is-continuing-medical-education", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/algorithm-development-for-training-and-optimisation", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/customer-segmentation", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/customer-segmentation/patient-segmentation-in-healthcare", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/health-economics-outcome-research", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/health-economics-outcome-research/thesis-vs-dissertation-differences-similarities", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/interpretation-reporting-and-visualisation", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/patient-journey-insights-machine-learning", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/patient-journey-insights-machine-learning/data-extraction-healthcare-definition-methods-applications", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/predictive-analytics", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/random-forests-biomedical-data-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/data-analytics-machine-learning/thought-leadership-content-editorial-design", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/book-editing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/manuscript-editing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/manuscript-editing/manuscript-editing-importance-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/manuscript-editing/top-benefits-of-manuscript-editing-services", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/post-editing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/proof-reading", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/proofreading", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/scientific-editing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/scientific-editing/scientific-developmental-editing-high-impact-journals", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/scientific-grant-review", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/thesis-editing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/thesis-editing-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/editing-and-translation/translation-with-editing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/education-editorial-service", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/education-editorial-service/accessibility-compliance", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/education-editorial-service/accessibility-compliance/web-accessibility-compliance-wcag-standards", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/education-editorial-service/ai-and-data-preparation-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/education-editorial-service/assessment-and-exam-review-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/education-editorial-service/digital-production-qa-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/education-editorial-service/learning-design-and-pedagogy", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/educational-content-development", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/marketing-communication-content-development-service", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/medical-data-collection", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/medical-data-collection/types-of-research-data-sources", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/medical-writing", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/medical-writing/editorial-quality-support-service", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/medical-writing/ich-guidelines-clinical-trials-drug-development", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/medical-writing/regulatory-writing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/medical-writing/regulatory-writing/ctd-structure-overview-modules", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/medico-legal-support-services", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/medico-legal-support-services/independent-medical-examinations-and-expert-assessments-in-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/medico-legal-support-services/medico-legal-support-services-healthcare", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/patient-education-content", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/patient-education-content/breast-cancer-treatment", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/patient-education-content/tuberculosis-treatment-symptoms-causes-diagnosis", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/case-report", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/case-report-writing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/case-report-writing/how-to-write-a-case-report", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/case-report/care-guidelines-case-reports", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/case-report/cspp1-variant-joubert-syndrome-metabolic-dysfunction", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/clinical-literature-review-for-an-evidence-based-medicine", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/clinical-literature-review-for-an-evidence-based-medicine/health-technology-assessment-hta-overview", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/customized-writing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/literature-search-and-citation", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/original-research-article", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/original-research-article/young-researchers-guide-original-research-article", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/patient-education-content", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/physician-manuscript", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/physician-manuscripts", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/physician-training", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/research-proposal", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/research-proposal/research-design-types-methods-best-practices", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/physician-writing-services/scopus-indexed-journals-submission-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/publication-support/art-work-preparation", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/art-work-preparation/cdsco-clinical-trial-approval-process-india", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/consort-guidelines-reporting-trials", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/double-blind-peer-review-definition-process", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/hipaa-compliance-complete-overview", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/how-to-implement-gpp-medical-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/icmje-guidelines-medical-research-compliance", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-manuscript-formatting-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-manuscript-formatting-services/citation-management-tools-formatting-referencing", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-manuscript-formatting-services/citation-styles-apa-ama-mla-vancouver-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-manuscript-formatting-services/manuscript-formatting-for-journal-submission", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/ckd-journal-selection-review", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/high-impact-academic-journals-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/identify-predatory-journals-2026", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/journal-citation-reports-impact-metrics-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/journal-rejection-key-reasons-tips-for-improving-manuscripts", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/journal-selection-alcoholic-liver-disease", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/journal-selection-incidence-melanoma-nonmelanoma-skin-cancers-india-global", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/journal-selection-manuscript-optimization", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/navigating-web-of-science-key-features-for-academic-success", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/right-journal-for-your-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/top-hybrid-journals-2025-trends-opportunities", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/top-journals-for-publication-in-2025-comprehensive-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-selection/understanding-cope-publication-ethics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-submission", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-submission/ai-tools-transform-academic-publishing", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-submission/complete-guide-to-writing-cover-letter-for-medical-journals", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-submission/guide-to-peer-review-types", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/journal-submission/mastering-journal-submission-guideline-with-ease", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/peer-review-pre-submission", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/plagiarism-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/plagiarism-services/meta-analysis-tools-medical-researchers", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/plagiarism-services/modern-plagiarism-detection", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/plagiarism-services/plagiarism-checking-in-publication", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/plagiarism-services/plagiarism-detection-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/poster-preparation", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/poster-preparation/european-society-for-medical-oncology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/poster-preparation/how-to-design-a-research-poster", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/poster-preparation/scientific-poster-preparation-guidelines", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/poster-preparation/why-scientific-design-and-visualization-matter-in-poster-preparation", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/responding-to-reviewers", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/responding-to-reviewers/rebuttal-preparation-peer-review-strategy", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/understanding-wame-medical-journal-editors", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/video-abstract", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/publication-support/video-abstract/create-perfect-video-abstract-research-paper", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/video-abstract/graphical-vs-video-abstracts-scientific-communication", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/publication-support/video-abstract/video-abstracts-enhancing-research-impact", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-impact", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/research-impact/graphical-abstract", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-impact/graphical-abstract/pck1-kidney-disease-mitochondrial-fitness", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-impact/graphical-abstract/research-visualization", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-impact/graphical-abstract/sox4-transcription-factor-kidney-fibrosis", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-impact/scientific-news-report", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-impact/scientific-news-report/scientific-news-reporting-for-researchers", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-impact/simplified-abstract-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-impact/simplified-abstract-services/sglt2i-phimosis-risk-men-diabetes", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/research-services/biostatistics-and-statistical-programming-service", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/biostatistics-and-statistical-programming-services", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/biostatistics-and-statistical-programming-services/biostatistical-programming-framework-regulatory-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/experimental-design", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/experimental-design/benefits-of-experimental-plan-in-research-and-design", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/grant-writing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/grant-writing/guide-to-grant-writing-strategies-success", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/grant-writing/research-grant-proposal-writing-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/literature-review-and-gap", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/literature-review-and-gap/drug-drug-interaction-literature-review-services-by-pubrica", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/literature-review-and-gap/literature-review-and-gap-literature-review-support-chronological-vs-thematic", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/literature-review-and-gap/literature-review-research-gap-services", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/literature-review-and-gap/open-access-research-impact", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/literature-review-and-gap/types-of-literature-review-in-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/medical-writing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/individual-participant-data-meta-analysis", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/introduction-to-bayesian-statistics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/meta-analysis-prisma-2020", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/meta-analysis-reporting-standards", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/meta-analysis-role-evidence-based-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/meta-analysis-services-prisma-2020", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/network-meta-analysis-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/meta-analysis/systematic-literature-review-vs-meta-analysis", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/new-product-discovery-and-development", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/product-development", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/product-development/sar-analysis-medical-statistics-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/scientific-writing", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/statistical-vs-contextual-interpretation-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/systematic-review", priority: 0.6, changeFrequency: "monthly" },
  { path: "/services/research-services/systematic-review-definition", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/systematic-review/how-to-conduct-a-systematic-review", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/systematic-review/risk-of-bias-assessment-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/systematic-review/swim-synthesis-without-meta-analysis-systematic-reviews", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/research-services/systematic-review/systematic-reviews-guide", priority: 0.5, changeFrequency: "monthly" },
  { path: "/services/scientific-communication", priority: 0.7, changeFrequency: "monthly" },
  { path: "/services/scientific-communication/technology-enabled-medical-scientific-communication", priority: 0.5, changeFrequency: "monthly" },

  // Subject Matter Experts
  { path: "/subject-matter-experts/agriculture", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/agrotechnology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/algorithm", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/algorithm/medical-insights-comprehensive-medical-algorithms", priority: 0.4, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/animal-science", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/augmented-reality", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/big-data-hadoop", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biocatalysts", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biochemistry", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biocomputing", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/bioengineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/bioinformatics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biomaterials", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biomedical-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biomedical-imaging", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biomolecular-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biomonitoring", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biophysics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biopolymers", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biostatistical-programming", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/biotechnology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/cancer-research", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/cardiology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/cardiovascular-biology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/cell-biology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/ceramic-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/chemical-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/cloud-computing", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/computer-science", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/cosmeceuticals", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/data-mining", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/dentistry", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/dermatology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/diabetology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/drug-delivery-system", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/e-learning", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/environmental-science", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/enzymes", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/food-processing", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/food-science", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/forensics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/genomics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/glycobiology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/gynecology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/internet-of-things", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/life-sciences", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/machine-learning", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/material-science", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/medical-animation", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/medical-imaging-techniques", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/medicinal-and-pharmaceutical-chemistry", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/medicinal-chemistry", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/molecular-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/nanobiotechnology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/nanotechnology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/neurology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/neuroscience", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/nuclear-chemistry", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/nuclear-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/nutraceuticals", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/optics-and-electronics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/peptides", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/pharmaceuticals", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/production-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/protein-engineering", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/psychiatry", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/psychology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/public-health", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/radiology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/robotics", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/sensor-technology", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/surgery", priority: 0.5, changeFrequency: "monthly" },
  { path: "/subject-matter-experts/tissue-engineering", priority: 0.5, changeFrequency: "monthly" },
];

async function safePosts(source: "academy" | "insights" | "blog" | "career" | "call-for-papers") {
  try {
    const { docs } = await getPosts({ source, limit: 1000 });
    return docs;
  } catch {
    return [];
  }
}

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const [academyPosts, insightsPosts, blogPosts, careerPosts, cfpPosts] = await Promise.all([
    safePosts("academy"),
    safePosts("insights"),
    safePosts("blog"),
    safePosts("career"),
    safePosts("call-for-papers"),
  ]);

  const dynamicEntries: { path: string; priority: number; changeFrequency: MetadataRoute.Sitemap[number]["changeFrequency"] }[] = [
    // Academy: urlPath already encodes the nested "category/slug" (or bare) shape used by the real route.
    ...academyPosts
      .filter((p) => p.urlPath)
      .map((p) => ({ path: `/academy/${p.urlPath}`, priority: 0.5, changeFrequency: "monthly" as const })),

    // Insights: route is flat-only (/insights/[slug]) regardless of urlPath nesting.
    ...insightsPosts
      .filter((p) => p.slug)
      .map((p) => ({ path: `/insights/${p.slug}`, priority: 0.5, changeFrequency: "monthly" as const })),

    // Blog: flat route, Payload-backed.
    ...blogPosts
      .filter((p) => p.slug)
      .map((p) => ({ path: `/blog/${p.slug}`, priority: 0.6, changeFrequency: "weekly" as const })),

    // Careers: urlPath encodes "job-posting/slug" for postings, bare slug otherwise.
    ...careerPosts
      .filter((p) => p.urlPath)
      .map((p) => ({ path: `/careers/${p.urlPath}`, priority: 0.5, changeFrequency: "weekly" as const })),

    // Call for papers: flat route.
    ...cfpPosts
      .filter((p) => p.slug)
      .map((p) => ({ path: `/call-for-papers/${p.slug}`, priority: 0.5, changeFrequency: "weekly" as const })),
  ];

  const seen = new Set<string>();
  const entries: MetadataRoute.Sitemap = [];

  for (const { path, priority, changeFrequency } of [...STATIC_ROUTES, ...dynamicEntries]) {
    const url = `${SITE_URL}${path}`;
    if (seen.has(url)) continue;
    seen.add(url);
    entries.push({ url, lastModified: new Date(), changeFrequency, priority });
  }

  return entries;
}
